[package]
name = "wings_utils"
version = "0.1.0-dev"
edition = "2021"
description = ""
repository = "https://github.com/thirdq/wings/"
license-file = "LICENSE"
keywords = ["wings"]

[dependencies]
bevy = "0.11.2"
rand = "0.8.5"
